version: "3.7"
services: 
    app:
        build: 
            args:
                user: mrs
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: estoque
        container_name: estoque-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - estoque

    db:
        image: mysql:5.7
        container_name: estoque-db
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICES_TAGS: dev
            SERVICE_NAME: mysql
        ports: 
            - 3306:3306
        volumes: 
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks: 
            - estoque

    nginx:
        image: nginx:1.17-alpine
        container_name: estoque-nginx
        restart: unless-stopped
        ports: 
            - 8787:80
        volumes: 
            - ./:/var/www
            - ./docker-compose/nginx/:/etc/nginx/conf.d
        networks: 
            - estoque

networks: 
    estoque:
        driver: bridge